name: Rust Project CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build Project
      run: cargo build
      working-directory: ./bioinfo_tool

    - name: Run Tests
      run: cargo test
      working-directory: ./bioinfo_tool

    - name: Generate Documentation
      run: cargo doc
      working-directory: ./bioinfo_tool

    - name: Run Clippy (Linting)
      run: cargo clippy -- -D warnings
      working-directory: ./bioinfo_tool

    - name: Check Formatting
      run: cargo fmt -- --check
      working-directory: ./bioinfo_tool
